### ISSUE TITLE
Consider using mac address instead for serial numbers

### ISSUE THREAD

**Issue by hmaarrfk** [sci-microscopy/illuminate#11]
Pro:
Never have to change define values when programming different boards.

Con:
Refractoring needed.
Need to understand this [Teansy 3 forum thread](https://forum.pjrc.com/threads/91-teensy-3-MAC-address/page5)

https://github.com/zfphil/illuminate/blob/e7a3544855fd38e02a1003d5aec41c71e6786786/illuminate/ledarray.h#L50

**Comment by zackphillips** [comment]
Wonderful idea!

**Comment by zackphillips** [comment]
Added Mac address printing to about command, SN and PN now persist with EEPROM.

**Comment by hmaarrfk** [comment]
I'm kinda curious, how did you ensure that SN and PN persist in EEPROM without being overwritten? Do you do 2 programming steps?

**Comment by zackphillips** [comment]
Yeah, It was a 2-step process. I used this script to do the writing the SN - Actually it's a good reminder to record these things in our books as well, so it doesn't mess up our workflow too much.

```c++
#include <EEPROM.h>
uint16_t pn_address = 100;
uint16_t sn_address = 200;

#define SERIAL_BAUD_RATE 112500

uint16_t sn = 18;
uint16_t pn = 4;

void setup() {
  // put your setup code here, to run once:
  byte lower_8bits_sn = sn & 0xff;
  byte upper_8bits_sn = (sn >> 8) & 0xff;
  EEPROM.write(sn_address, lower_8bits_sn);
  EEPROM.write(sn_address + 1, upper_8bits_sn);

  byte lower_8bits_pn = pn & 0xff;
  byte upper_8bits_pn = (pn >> 8) & 0xff;
  EEPROM.write(pn_address, lower_8bits_pn);
  EEPROM.write(pn_address + 1, upper_8bits_pn);

  Serial.begin(SERIAL_BAUD_RATE);

  // Read SN and PN from EEPROM
  uint16_t sn_read = (EEPROM.read(sn_address + 1) << 8) | EEPROM.read(sn_address);
  uint16_t pn_read = (EEPROM.read(pn_address + 1) << 8) | EEPROM.read(pn_address);

  Serial.print(F("Set board part number to "));
  Serial.print(pn_read);
  Serial.print(", SN# ");
  Serial.println(sn_read);
}

void loop() {



}
