### ISSUE TITLE
`fill_array` and uneven pattern

### ISSUE THREAD

**Issue by hmaarrfk** [sci-microscopy/illuminate#12]
I understand the way you plug in power might affect the boot up sequence since the Teansy and LED driver chips are powered by different supplies.

I also reboot the Teansy upon initialization in python. 

As you mentionned, the recent updates might fill fix the `fill_array` issue, but maybe I am hitting a different one now?

It seems to be a brown out issue but I'm not really sure. See the video attached. Pseudo code (or at least, code that uses my library).

```python
from pyilluminate import Illuminate
light = Illuminate()  # reboot is called inside here
light.brightness = 20
light.fill_array()

# light.clear()  # running clear before fill_array again seems to fix things.
# Run this line as many times as needed
light.fill_array()
```

I don't know what the best way to address is:
1. In (as I am doing now). `fill_array` just calls `clear`, then issues the `ff` command. But one would need to do this for many other commands too.
2. At the microcontroller level: issue a clear command before turning anything on?

**Comment by zackphillips** [comment]
I was able to replicate this - When the device is drawing a lot of current, the supply line is more noisy, causing the TLC chips to miss-read bits. This could be a supply issue or a board issue, it's tough to tell. I fixed this by adding a clear() call before the device fills the array. Commit 2fe9d96 should not longer have this issue (tested with your board)

This is basically what you suggested in your second point, thanks!

**Comment by hmaarrfk** [comment]
Anyway to put this within the `drawCircle`. Seems like it might fix issues for other boards that use the bright field/dark field patterns.

I would suggest maybe adding it to an even lower level routine (so that it propagates to the `l.LED#1.LED#2.LED#3` command, but seems tricky to add it to `setLed`.

**Comment by zackphillips** [comment]
That's a bit of a hack, but I can't think of any reason why it would cause issues. If you're calling any command which uses drawCircle you probably don't care about the extra ~100ms it takes to clear the array before, anyway. Just pushed another commit.

**Comment by hmaarrfk** [comment]
Yeah, that blinking was quite obvious. I couldn't figure out if it was from python or the Teansy.
