### ISSUE TITLE
Add setBrightness command in addition to setColor

### ISSUE THREAD

**Issue by zackphillips** [sci-microscopy/illuminate#17]
setColor currently handles both color and brightness. Adding a seperate brightness command would help disambiguate this.

## Ideas
setColor has the same bit-depth as setBrightness, but is converted to a floating point number after input. This is used to scale the brightness to the correct value.

## Roadmap
- Make setColor set normalized values (floating-point, (0,1))
- Add setBrightness command
- Remove ability to set brightness with color

**Comment by hmaarrfk** [comment]
Has this been implemented already?

**Comment by zackphillips** [comment]
Yep, closing now
