### ISSUE TITLE
Ultra large LED bowl doesn't seem to work with recent version

### ISSUE THREAD

**Issue by hmaarrfk** [sci-microscopy/illuminate#21]
I was playing with the large LED bowl and it doesn't seem to turn on with more recent versions of the software. We definitely had to go backward to an older version.

I think maybe it has something to do with the super large buffer we enabled at some point.

**Comment by zackphillips** [comment]
Looking into this before the end of the week!

**Comment by zackphillips** [comment]
Latest version seems to fix this... let me know if you have time to test. Just an issue with memory management, these devices have trouble with >1300 LEDs without reasonable allocation practices. Dynamic allocation seems to be a bad idea in general...

**Comment by zackphillips** [comment]
I don't have any more of these devices to test on so I'm just using the center board :D

**Comment by hmaarrfk** [comment]
Yeah, memory is always an issue I hate dealing with.
You have to throw away all your "clean code rules" when working with these
tiny processors.
