### ISSUE TITLE
scan_full doesn't actually output the LED list

### ISSUE THREAD

**Issue by hmaarrfk** [sci-microscopy/illuminate#7]
```COMMAND:
scf / scanFull
SYNTAX:
scf,[delay_ms]
DESCRIPTION:
Scan all active LEDs. Sends trigger pulse in between images. Outputs LED list to serial terminal.
```

I just get newlines `\n` (the total number which depends on the delay) until I receive the ` -==- \n`.

I also think that the `,` (comma) is a typo. Should it be a period `.`?

**Comment by zackphillips** [comment]
Should be fixed in 102ee1d
