### ISSUE TITLE
Multi-line print statements should be consolidated into printf

### ISSUE THREAD

**Issue by zackphillips** [sci-microscopy/illuminate#9]
Multi-line print statements are hard to look at, we should change them to printf statements. As an example, a poorly constructed output is:
`    Serial.print(F("Sequence bit depth is now: "));
    Serial.print(LedArray::led_sequence.bit_depth);
    Serial.print(SERIAL_LINE_ENDING);`

While the "pretty" version would be:
`printf("Sequence bit depth is now: %d %s", LedArray::led_sequence.bit_depth,SERIAL_LINE_ENDING)`

**Comment by hmaarrfk** [comment]
If you want, you can avoid the `%s` for `SERIAL_LINE_ENDING` by having:

```cpp
#define SERIAL_LINE_ENDING "\n"
....
printf("Sequence bit depth is now: %d " SERIAL_LINE_ENDING, LedArray::led_sequence.bit_depth);
```

The compiler will automatically concatenate string constants for you.

**Comment by zackphillips** [comment]
Nice! Probably not worth doing for every single one which has already been changed, but good to know in the future. I think this should be fixed at this point but feel free to open another bug or create a pull request if you find specific issues.

**Comment by hmaarrfk** [comment]
Def not worth it.

yeah, python `strip` takes care of both `\n` and `\r`. I kinda strip the new lines and add them back, kinda redundant, but at least it works and is robust.
